apiVersion: v1
entries:
  dataspace-connector:
  - apiVersion: v2
    appVersion: 0.0.1-SNAPSHOT
    created: "2022-12-09T13:16:45.1043765+01:00"
    description: A Helm chart to deploy the Eclipse Dataspace Connector to Kubernetes
    digest: 3c5f5bab1b59b543f69edd82338371e8812a4af662b0e629b38879081ff4d8e0
    name: dataspace-connector
    type: application
    urls:
    - dataspace-connector-0.0.3.tgz
    version: 0.0.3
generated: "2022-12-09T13:16:45.1033477+01:00"
